# Generated by Django 4.0 on 2022-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_alter_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
